<a href="https://colab.research.google.com/github/hang-1n-there/pytorch_learn/blob/main/%ED%85%90%EC%84%9C_%EC%8B%A4%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

언더바 추가 시 call by reference

In [ ]:
a=torch.FloatTensor([[1,2],[2,3]
                     ,[3,4],[5,6]])
b=torch.FloatTensor([[1,2],[2,3]
                     ,[3,4],[5,6]])

print(a.mul(b))
print(a)
print(a.mul_(b))
print(a)

tensor([[ 1.,  4.],
        [ 4.,  9.],
        [ 9., 16.],
        [25., 36.]])
tensor([[1., 2.],
        [2., 3.],
        [3., 4.],
        [5., 6.]])
tensor([[ 1.,  4.],
        [ 4.,  9.],
        [ 9., 16.],
        [25., 36.]])
tensor([[ 1.,  4.],
        [ 4.,  9.],
        [ 9., 16.],
        [25., 36.]])


dim=0(axis=0) : 1차원
dim=1(axis=1) : 2차원

In [ ]:
print(a.sum(dim=0))
print(a.sum(dim=-1))

tensor([39., 65.])
tensor([ 5., 13., 25., 61.])


squeeze : 특정 차원이 1인 경우 삭제
unsqueeze : 정해진 차원에 1을 추가

In [ ]:
print(a.unsqueeze(2).size())
print(a.squeeze().size())

torch.Size([4, 2, 1])
torch.Size([4, 2])
